name: Regression
run-name: Regression test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

#      - name: Setup Chrome Browser
#        run: |
#          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
#          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
#          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
#          sudo apt-get -y update
#          sudo apt-get -y install google-chrome-stable

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@latest
        with:
            chrome-version: 'stable' # or specify a version number



      - name: Run Regression Tests
        run: mvn test -Dcucumber.filter.tags="@db_only"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Smoke Test Results HTML File
          path: target/cucumber-report/report.html

      - name: Send failure email
        if: failure() # Only run this step if the workflow fails
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Regression tests failed
          body: Check the failed workflow run at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: duotechinstructor@gmail.com
          from: dtacademyb10@gmail.com

      - name: Notify Slack on Failure
        if: failure() # Only run this step if the workflow fails
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#class-resources'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}